apiVersion: v1
kind: PersistentVolume
metadata:
  name: asiayo-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-storage-class
  awsElasticBlockStore:
    volumeID: vol-12345678
    fsType: ext4
